#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./scripts/autopush.sh "short message"
# If no message is provided, it will use a default message.

MSG="${1:-update}"
BASE_BRANCH="${BASE_BRANCH:-main}"
REMOTE="${REMOTE:-origin}"
LOGFILE="${LOGFILE:-CHANGELOG.md}"

# 0) sanity checks
git rev-parse --is-inside-work-tree >/dev/null

# 1) ensure base branch exists locally (best effort)
#    (If you're currently on another branch, we won't force checkout BASE_BRANCH;
#     we'll just target PR base as BASE_BRANCH.)
git show-ref --verify --quiet "refs/heads/${BASE_BRANCH}" || true

# 2) if no changes, exit
if git diff --quiet && git diff --cached --quiet; then
  echo "[autopush] no changes, skip."
  exit 0
fi

# 3) create a new auto branch
ts_utc="$(date -u +"%Y-%m-%d %H:%M:%SZ")"
ts_compact="$(date -u +"%Y%m%d-%H%M%S")"
BRANCH="auto/${ts_compact}"

# Create branch from current HEAD (so it captures what Codex just changed)
git checkout -b "${BRANCH}"

# 4) write changelog entry (tracked in repo)
#    Use porcelain status as a compact file list
summary="$(git status --porcelain | sed 's/^/  - /')"

{
  echo ""
  echo "## ${ts_utc} — ${MSG}"
  echo ""
  echo "${summary}"
} >> "${LOGFILE}"

# 5) stage + commit
git add -A
git commit -m "Auto: ${MSG} (${ts_utc})"

# 6) push branch
git push -u "${REMOTE}" "${BRANCH}"

# 7) create PR (if gh is available and authenticated)
if command -v gh >/dev/null 2>&1; then
  # Check auth status (best effort)
  if gh auth status >/dev/null 2>&1; then
    # Build PR title/body
    PR_TITLE="Auto: ${MSG} (${ts_utc})"
    PR_BODY="$(cat <<EOF
This PR was generated by scripts/autopush.sh.

Changes:
${summary}

Notes:
- Base branch: ${BASE_BRANCH}
- Branch: ${BRANCH}
EOF
)"
    # Create PR (avoid failing if PR already exists)
    gh pr create --base "${BASE_BRANCH}" --head "${BRANCH}" --title "${PR_TITLE}" --body "${PR_BODY}" \
      || echo "[autopush] PR creation failed or PR already exists. You can create it manually."
    echo "[autopush] done (branch pushed, PR attempted)."
  else
    echo "[autopush] 'gh' found but not authenticated."
    echo "           Run: gh auth login"
    echo "           Then create PR manually: gh pr create --base ${BASE_BRANCH} --head ${BRANCH}"
  fi
else
  echo "[autopush] GitHub CLI 'gh' not found."
  echo "           Option A: install gh and run: gh auth login"
  echo "           Option B: create PR on GitHub UI from branch ${BRANCH} -> ${BASE_BRANCH}"
fi
